name: VillagerSaver
version: 1.2.1
authors: [MarioFinale, Kasama]
main: cl.mariofinale.villagerSaver
api-version: 1.16
website: https://github.com/MarioFinale/VillagerSaver
commands:
  villagersaver:
    description: VillagerSaver commands.
    usage: /villagersaver <blacklistworld - unblacklistworld>