name: VillagerSaver
version: 1.4.1
authors: [MarioFinale, Kasama, Kyle Hunady]
main: cl.mariofinale.VillagerSaver
api-version: '1.20'
website: https://github.com/MarioFinale/VillagerSaver
commands:
  villagersaver:
    description: VillagerSaver commands.
    usage: /villagersaver <blacklistworld - unblacklistworld>