name: VillagerSaver
version: 1.2.2
authors: [MarioFinale, Kasama]
main: cl.mariofinale.villagerSaver
api-version: 1.17
website: https://github.com/MarioFinale/VillagerSaver
commands:
  villagersaver:
    description: VillagerSaver commands.
    usage: /villagersaver <blacklistworld - unblacklistworld>